### ISSUE TITLE
We can't release new versions on RubyGems

### ISSUE THREAD

**Issue by patbl** [academia-edu/simple-sitemap#6]
Ryan Lower is the only owner. I emailed him twice, in April and May of 2017, but he didn't respond.

I think these are our options:

* Have someone he knows better (Richard, Ben, or Nate) email him.
* Contact someone at RubyGems, prove to them that we own the repository, and ask them to make developers@academia.edu an owner.
* Rename the gem (Awesome Sitemap?).

**Comment by yn-academia** [comment]
How about "simple_sitemap_furl"

**Comment by yn-academia** [comment]
Apparently he works at Stripe. https://twitter.com/ryanlower We could ask djudd to track him down

**Comment by mitchellwfox** [comment]
Richard emailed him. We'll see if he replies. Patrick mentions there is also another person we could try:

we could also try contacting Stacey Lynn. She's also an owner; I just wasn't able to identify her at first by her RubyGems user name. Here's her Facebook account: https://www.facebook.com/capicue

**Comment by patbl** [comment]
Richard took care of this, richard++
